monolog:
    # Настройка доступных каналов
    channels:
        - deprecation
        - database
        - customlog
        - DivisionService
        - TeamService
        - AllMatchesService
        - PlayoffService
        - GenerateMatchController
        - DatabaseServiceT
        - Custom2

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/test_%kernel.environment%.log"
            process_psr_3_messages: true
            level: debug
            channels: ["DivisionService","TeamService", "AllMatchesService", "PlayoffService","GenerateMatchController"]
            formatter: App\Monolog\MonologConfigurator

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            formatter: monolog.formatter.line

        database_log:
            type: stream
            path: "%kernel.logs_dir%/database.log"
            level: debug
            channels: ["database"]
            formatter: monolog.formatter.line



# when@test:
#     monolog:
#         handlers:
#             main:
#                 type: fingers_crossed
#                 action_level: error
#                 handler: nested
#                 excluded_http_codes: [404, 405]
#                 channels: ["!event"]
#             nested:
#                 type: stream
#                 path: "%kernel.logs_dir%/%kernel.environment%.log"
#                 level: debug

# when@prod:
#     monolog:
#         handlers:
#             main:
#                 type: fingers_crossed
#                 action_level: error
#                 handler: nested
#                 excluded_http_codes: [404, 405]
#                 buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#             nested:
#                 type: stream
#                 path: php://stderr
#                 level: debug
#                 formatter: monolog.formatter.json
#             console:
#                 type: console
#                 process_psr_3_messages: false
#                 channels: ["!event", "!doctrine"]
#             deprecation:
#                 type: stream
#                 channels: [deprecation]
#                 path: php://stderr
#                 formatter: monolog.formatter.json
#             database_log:
#                 type: stream
#                 path: "%kernel.logs_dir%/database.log"
#                 level: debug
#                 channels: ["database"]
